### ISSUE TITLE
ProbeController rpc on Controller service

### ISSUE THREAD

**Issue by jeffpak** [container-storage-interface/spec#102]
Hello,

We are wondering why there is no dedicated RPC for probing the controller's readiness, when there is one for the node. We noticed it was difficult to determine whether or not we had a functioning controller until we started creating volumes, which seems a bit late in the lifecycle. It would be great to have a dedicated probe request for the controller in addition to the node.

Looking forward to your thoughts.
-Diego Persistence Team for Cloud Foundry

**Comment by akutz** [comment]
Hi @jeffpak,

Hmmm. This is curious. While some storage platforms enable centralized creates with no host dependencies, there are still yet those that *do* require host dependencies, especially with regards to potential configuration and permissions issues. Imagine a virtual filesystem (VFS) plug-in that lacks permissions to write to the local filesystem? Or an Amazon Elastic Block Service (EBS) plug-in that lacks the configured credentials or role to create new volumes?

Today any of the above errors could be handled by the Controller plug-in failing to start and providing some error to the CO.

However, if that's the intended behavior it begs the question why not follow the same pattern for the Node?

I agree that the Controller and Node should either:

* Both implement a `Probe` RPC to indicate if the service is configured correctly and has the required dependencies.
* Both return an error on start to the CO with the same result that would otherwise be returned from their respected `Probe` RPCs.

I personally like the `Probe` approach as it follows the pattern of a type registry where a constructor should never return an error and some associated initialization call is what is allowed to return the failed state based on config/dependency issues. This way it's at least possible to validate a plug-in can load and be recognized by the CO even if the plug-in is not properly configured. That has value for dev and testing.

**Comment by jdef** [comment]
I tend to agree: consistency is important. Thanks for this proposal. Would like to hear from some others @jieyu @saad-ali @cpuguy83 @julian-hj

**Comment by julian-hj** [comment]
+1 to add a ProbeController method

**Comment by saad-ali** [comment]
SGTM

**Comment by j-griffith** [comment]
Seems like it would be easy enough to implement and certainly useful IMO

**Comment by cpuguy83** [comment]
SGTM

**Comment by Kaixiang** [comment]
Hi,

This is Kai from Diego Persistence Team for Cloud Foundry,
I've submitted a PR implementing this, Could you help review it?

Regards

**Comment by jdef** [comment]
We've iterated on this a few times. Currently, Probe() has been reimagined as a health-checker and is part of the Identity service. There was a proposal somewhere to ditch Probe in favor of gRPC health checks (https://github.com/grpc/grpc/blob/master/doc/health-checking.md): https://github.com/container-storage-interface/spec/issues/171#issuecomment-366422398 but we haven't taken the step yet of importing any non-CSI protos into the spec.
