### ISSUE TITLE
spec: clarify expectations related to possibly failed CreateVolume calls and volume deletion

### ISSUE THREAD

**Issue by jdef** [container-storage-interface/spec#110]
continuation of discussion here: https://github.com/container-storage-interface/spec/pull/88#issuecomment-330918121

* there's an implied relationship between LIST_VOLUMES and CREATE_DELETE capabilities for some cases
* we're expecting that a DC operator may be involved with cleanup for some cases

The spec should talk about these things so that it's clear to both COs and plugins what the specific expectations are.

**Comment by akutz** [comment]
Hi @jdef,

I'm going to try and echo a discussion I had with my colleague @codenrhoden re: this topic. The context of our conversation was the [CSI-NFS](https://github.com/codedellemc/csi-nfs) plug-in he authored. Travis noted that it does not support `LIST_VOLUMES` because he saw no point. We surmised that for an NFS plug-in to implement `LIST_VOLUMES` either one or more of the following would have to be true:

1. The Controller service would need to run on the NFS server.
2. <a name="nfs-config"></a>The Controller service running on the Node hosts (which are presumably **not** the NFS server) would be configured via environment variable with the IP address of the NFS server to use. This in conjunction with the command `showmount -e` would allow a Controller service on a Node host to list volumes -- albeit only for pre-configured NFS server.

So in the end @codenrhoden elected **not** to implement the `LIST_VOLUMES` RPC as he saw little point, and the RPC **is** listed as `OPTIONAL`. However, as you illustrate in this issue's description, there appears to be an undocumented relationship between the capabilities `LIST_VOLUMES` and `CREATE_DELETE`.

I believe the following list summarizes the conclusions reached by @codenrhoden and myself, but I expect Travis will jump in and correct me if I'm mistaken:

* The spec needs to call out the relationship between `LIST_VOLUMES` and `CREATE_DELETE`.
* The spec needs to **explicitly** call out the workflows and possibly UX decisions COs should support in regards to a plug-ins advertised capabilities. For example, if a Controller service reports `PUBLISH_UNPUBLISH_VOLUME` but not `LIST_VOLUMES`, a CO should be **required** to implement a UX that is able to transition to some advanced/manual mode that enables a user to manually enter a volume's ID. With respect to the [CSI-NFS](https://github.com/codedellemc/csi-nfs) plug-in this would be the NFS export fully-qualified URI. This addresses [issue two](#user-content-nfs-config) from the previous list as the NFS server's IP address would be included in the specified volume handle's ID.

@codenrhoden, does that accurately summarize our discussion with respect to this issue?

**Comment by codenrhoden** [comment]
@akutz thanks for writing that up. I agree with what you wrote, and have some additional input. What I was noticing was more an implicit relationship between `LIST_VOLUMES` and the ability for a plugin to work with **pre-provisioned** volumes.  As called out @ https://github.com/container-storage-interface/spec/issues/103#issuecomment-330914383, it is now expected that a CO call `ListVolumes` before doing a `ValidateVolumeCapabilities`, in essence to get the `name`, which is now a required field.  When I wrote `csi-nfs`, this was not the case, and the volume was uniquely identifiable by it's metadata, namely something like `host=192.168.75.2 export=/data` in its metadata. NFS volumes don't really have a name per se, so it was never used.

As you pointed out, I saw no need to implement `ListVolumes` because the plugin I created was intended to *only* work with pre-provisioned volumes, and the plugin wouldn't know what server to list volumes from. I didn't want to accept an open-ended list of server addresses to query (that could get expensive), and I didn't want to require the plugin to be configured to point to a single server (reducing the plugin's usefulness). As it is right now, if you give it a valid server and export, it will mount/unmount it (assuming that the client is allowed by the export). So, my take wasn't related to create/delete so much as it was that the new paradigm makes a requirement that any plugin that wants to support pre-provisioned volumes also has to support `ListVolumes`, which makes sense on its surface, but is not without it's own issues. There is no real concept of a "name" for an existing NFS share, the old way of having the volumeID be a map worked fine, but I can definitely serialize the map into `name` to make that work. It's just unnecessary from the plugin's perspective. Always having a name brings in lots of benefits, as @akutz has elaborated elsewhere.

But for me, the real scenario I don't understand (and what @akutz is getting at with the UX piece), is how does a CO work with a user to reference a pre-provisioned volume? Before today, I had assumed that a user would have to provide all the info that went into that old `VolumeID`, for NFS, this would be the IP and share name (it was not hard to picture this in defined in a k8s YAML file), but what I've heard now is that a user is only expected to give the `name`. But where does that name come from? Can they be expected to know it ahead of time? It sounds like it comes from `ListVolumes`. The `name` in that case is constructed in a plugin-specific way, so that means that a user has to be shown a list of volumes so they can pick it. 

Since `listVolumes` is an optional RPC, at least calling out that pre-provisioned volume support depends on implementing `ListVolumes` would be an improvement. (assuming my understanding of all this is correct)

Selfishly, I'm still not sure what the best approach is for an NFS plugin to implement `ListVolumes`. I had not envisioned telling the plugin anything about available NFS servers, but that seems inevitable now.

**Comment by codenrhoden** [comment]
FYI, I updated my above comment (sorry for those reading on email), because I had confused myself on `name` vs `id`, where `id` is in the VolumeHandle. The previous version of my comment was based on a world that did not exist, one where a volume `name` was used everywhere instead of a VolumeHandle as proposed in #103. Apologies.
