### ISSUE TITLE
ListVolumesResponse should return an ID

### ISSUE THREAD

**Issue by lpabon** [container-storage-interface/spec#138]
The current model which provides a StartToken on ListVolumesRequest does not provide enough information if there are multiple clients to the CSI driver. For this reason ListVolumesResponse should return an ID that is passed in with StartToken to identify the caller.

Unless grpc provides a method to get some type of id from the connection?

**Comment by jdef** [comment]
I don't understand the need for clientID. Can you provide an example
workflow that illustrates why a plugin needs to identify unique clients?

**Comment by akutz** [comment]
Hi @jdef,

Isaw @lpabon's post and started considering this situation myself. First of all, gRPC does *not* provide a unique connection identifier. The reasoning, IMO, [is faulty](https://groups.google.com/forum/#!msg/grpc-io/GZum7Bu6DyE/3MUDI3p4FwAJ):

> gRPC does not provide this level of functionality, because it isn't valid when proxies are used and even sometimes when they're not.

This is also true for HTTP and does not stop people from using it when it is available. Too much of Go and gRPC seems to be based around what works 100% of the time and not providing tools that work in a large number of cases. I digress.

Anyway, the reason @lpabon likely brings this issue up is due to concern that paging data requires knowledge of the client requesting the next page. I can see the point, but I'd counter that since the token is a string, it could easily be enhanced by the SP like so:

```json
{
  "i": "bda5c39bdd22448d9c8c6ae211a7265e",
  "c": 800
}
```

A minified version of the above JSON would be:

```json
{"i":"bda5c39bdd22448d9c8c6ae211a7265e","c":800}
```

The above could even be base-64 encoded:

```shell
eyJpIjoiYmRhNWMzOWJkZDIyNDQ4ZDljOGM2YWUyMTFhNzI2NWUiLCJjIjo4MDB9
```

My point is that an SP **can** define a token string to be whatever the SP desires -- and is **opaque** to the CO. The key to the above token is that it includes **two** pieces of information:

1. `i`: The token's unique ID that **any** client can use. This ID might also be associated with the page data TTL.
2. `c`: The cursor that points to the next element/page to return.

However, @jdef, this is why I think you're confused as to the need for the client ID. I think @lpabon believes the token should include a unique ID **and** the cursor, and I think you, @jdef, probably think the token only needs to be a unique ID.

I think I agree with @jdef here (if I'm even half correct in my assumptions).

While I can see how a token could be nothing more than a simple integer cursor, or could be enhanced to be a JSON object that includes a unique ID **and** a cursor, as well as any other useful information, I believe ultimately an SP should simply return a unique ID. That ID can be the same for the duration of the paged data, or the ID could change every time a new page is requested. Regardless, the token should be something the SP uses to query its own cache/datastore/storage provider for the next page.

I do not think it's the job of the token to persist information about the client/cursor, but rather the SP uses the token to look up that information in a manner completely opaque to the CO and user.

**Comment by akutz** [comment]
A quick addendum -- as far as identifying the client with respect to the token goes, it's my opinion that a token for purposes of paging data is a bearer token -- he/she who possesses the token gets the data.

**Comment by jdef** [comment]
Another argument I'd like to present: CSI doesn't make any distinction
among CO's invoking the same plugin instance's RPC for any other call in
the spec, why should it do so for ListVolumes? Yes, I was thinking that the
paging token would be a bearer token. It could also encode multiple pieces
of information as suggested by @akutz, if needed. At the end of the day,
it's opaque to the CO so the plugin can basically do whatever it wants w/
respect to encoding data in the token, subject to the field size
limitations proposed by #132

On Sat, Nov 4, 2017 at 9:51 PM, Schley Andrew Kutz <notifications@github.com

**Comment by lpabon** [comment]
Here is an example:

```
[ client 1 ] --> |
                      | --> [ csi driver ]
[ client 2 ] --> |
```

If two clients are connected to the CSI driver and both clients send a `ListVolumes( maxEntries = M )` for client 1 at time `t1` and `ListVolumes( maxEntries = N )` for client 2 at time `t2`, then how does the driver maintain state to be able to return the correct token for that point-in-time view of volumes?

Currently there is no model to uniquely identify each of these clients.

**Comment by codenrhoden** [comment]
This seems related to #104 as well

**Comment by akutz** [comment]
Hi @codenrhoden,

Maybe.

Hi @lpabon,

I'm not sure I understand. The token returned by `ListVolumes` is a bearer token used by a client to ask for the subsequent data page. Your use case is already handled by the spec.

**Comment by lpabon** [comment]
Ah, I see @akutz . By a bearer token you mean that it is up to the driver to marshal/unmarshal data into the token to be able to continue with pagination from a specific client. I am ok with this model as long as we describe this on the comments for `next_token`

**Comment by lpabon** [comment]
Ah, I see @akutz . By a bearer token you mean that it is up to the driver to marshal/unmarshal data into the token to be able to continue with pagination from a specific client. I am ok with this model as long as we describe this on the comments for `next_token`

**Comment by lpabon** [comment]
I should leave open to add this documentation to the spec.
