### ISSUE TITLE
Controller service should be optional

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#162]
Today there the following calls exist:
* `Controller` service
  * `ControllerGetCapabilities()`
* `Node` services
  * `NodeGetCapabilities()`

A call to `ControllerGetCapabilities()` is required to determine if a plugin implements the `CreateVolume()` or `NodePublishVolume()` calls.

If a volume plugin does not implement any of the `Controller` service capabilities, it should not have to implement the `Controller` service. To enable this we should move `GetCapabilities()` in to the `Identity` service.

**Comment by jdef** [comment]
Controller currently has two non-optional calls: ControllerProbeNode and ValidateVolumeCapabilities that are not reflected via the result of GetControllerCapabilities.

**Comment by jdef** [comment]
In one of the meetings (community, I think) someone also mentioned a generic API, as part of `Identity`, by which service extensions could be enabled - sounds similar to #6

**Comment by saad-ali** [comment]
Clarifying the original issue:

Volume Plugins like NFS only have Node operations (no controller operations). We should modify the spec to allow such volume plugins to not implement controller service.

To make this happen, I suggest the following:
* Add "global" capabilities in the Identity service. This could be, for example, a capability to indicate if the plugin implements the controller service.
* Optionally, consider if we can remove capabilities from Node and Controller service and only have global capabilities in the Identity service.
* Figure out how to handle `ValidateVolumeCapabilities(...)`. Should that be moved to node service or Identity service? Or can we leave it in Controller and assume it is not needed if a plugin does not implement controller service (it doesn't implement a CreateVolume call).

**Comment by akutz** [comment]
Hi @saad-ali,

> Figure out how to handle ValidateVolumeCapabilities(...). Should that be moved to node service or Identity service? Or can we leave it in Controller and assume it is not needed if a plugin does not implement controller service (it doesn't implement a CreateVolume call).

Perhaps implement a `Capabilities` service that is home to any capabilities-related RPCs, such as `ValidateVolumeCapabilities`, `GetControllerCapabilities`, `GetNodeCapabilities`, etc. Like the `Identity` service the `Capabilities` service would exist on all hosts.

Alternatively, a suggestion to which I'm partial is to consolidate all RPCs into a single service and control which RPCs are available purely via the Capabilities enum. That way whether certain operations are available are totally dependent upon the advertised capabilities, and there's a single service so no need to wonder how to divide up functionality.

**Comment by jdef** [comment]
Some other reasons that we have the `ValidateVolumeCapabilities` RPC:

1. The plugin supports pre-existing volumes and the controller doesn't support Create/Delete, but does support List. In this case the CO SHOULD invoke Validate to confirm that a user can consume a volume reported by List using some given set of capabilities. Maybe this makes sense for an NFS plugin, maybe not (maybe there is a list of NFS shares stashed in a central repo somewhere that can be returned by a call to List?).

2. The plugin supports pre-existing volumes and the controller doesn't support Create/Delete, or List. In this case the CO should invoke Validate to confirm that a user a consume a volume whose parameters are manually constructed by said user, given some set of requested capabilities. IMO this is more likely the case for an NFS, CIFS, or SSHFS plugin; the available shares on the network are managed out-of-band w/ respect to the CO and a user wants to connect their workload to one of those shares. The CO can call ValidateVolumeCapabilities prior to workload scheduling/placement to validate the share parameters enter by a user.

3. Are there other use cases / reasons that a CO wants to call ValidateVolumeCapabilities? if so, let's capture them.

I'd also like to address the "monolothic service" vs. "specialized services" ideas presented by @akutz. With either approach there's a set of complexity to deal w/ regarding the determination of which capabilities are supported by some plugin, and specific tradeoffs regarding to the "burden" of implementation on the plugin side:

(A) The monolithic approach forces some implementations using certain languages (like Golang) to implement EVERY RPC, even if most of them are not supported; it also reduces the cohesiveness of the API. For plugins which are distributed across master and worker nodes in the cluster using separate "master" and "worker" variants, it's likely that many RPCs for each of the variants will be unused and return a "not implemented" code. There's still the burden of understanding the possible interaction between various RPCs -- even if they're all in one mega-service, the SP still has the burden of determine whether an RPC X needs to be implemented because the plugin wants to expose RPC's A, B and C (this shifts the burden from where it is today).

(B) The specialized approach adds some cognitive overhead by grouping related RPCs into specific services, improve cohesiveness; however, if a specialized service has optional RPCs then that service requires an additional RPC that the CO SHOULD query to determine which RPCs are supported. Interactions between RPCs of different services are noted in the spec and it's the burden of every SP to implement an entire service even if only 1 of its RPCs is REQUIRED for some workflow.

(C) Future: the use of optional, specialized services probably requires *another* RPC at some level (perhaps Identity) to determine which optional services are provided by plugin. Consider an optional Snapshot service, for example. Optional, specialized services also take further us down a path where there may be overlap/interactions/dependencies between services that are not super-obvious at first. At the moment we're probably closer to the specialized services end of the spectrum, and we don't have any optional, specialized services.

... all that said ...

If we made `ValidateVolumeCapabilities` optional (always), then we're making it very hard for CO's to pre-validate user-created volume structs prior to container scheduling and runtime, where calls are then made to the NodeXXX APIs. Is that acceptable?

If so, we could break-out `ValidateVolumeCapabilities` into an optional, specialized "Validation" service with a single, REQUIRED RPC, and at the same time expand the API of the Identity service with an IdentityGetCapabilities RPC that would indicate which RPC services are supported by the plugin instance: for example, the Node + Validation service (Identity is always required and is not optional service). This takes us down the road of optional, specialized services. Are we ready for this additional complexity at this point?

I'm hesitant to blindly trust user input and to NOT provide a CO any way to validate volume capabilities until resources are already scheduled and there's a container-placement or container-startup operation in progress. Making the validation API completely optional seems to give SPs the opportunity to do exactly this.

A related approach would make ValidateVolumeCapabilities OPTIONAL in some cases and REQUIRED in others. In general I'm not a fan of this because I think it convolves the API.

**Comment by akutz** [comment]
Hi @jdef,

I don't disagree with your statements, but this isn't a valid argument IMO:

> The monolithic approach forces some implementations using certain languages (like Golang) to implement EVERY RPC, even if most of them are not supported

Of course it would. We have that issue today with anything made optional.

> A related approach would make ValidateVolumeCapabilities OPTIONAL

Well, that still has to be implemented by Golang. You simply mark it as `Unimplemented` in the returned error.

Being forced to implement optional RPCs in languages like Golang isn't a good argument against a monolithic service when there are already several optional RPCs today, and your discussion suggests yet another.

**Comment by jdef** [comment]
@akutz The point I was trying to make was that with a monolithic approach, the "you must write code for all RPCs in the spec, for all plugin objects, period" has negative consequences for implementations: let's call these consequences "boilerplate garbage" for now (even if that's not the best way to categorize it).

Today it's possible to write an Identity+Controller plugin and Identity+Node plugin pair that may be distributed across master and worker nodes respectively. In such an arrangement, the spec as it stands today requires less boilerplate garbage than would a spec that combines ALL of the RPCs into a monolithic service.

Furthermore, if we make ValidateVolumeCapabilities optional (somehow) to enable plugins that only consist of Identity+Node (in a spec similar to what we have today) then you keep the noise of the boilerplate garbage to a minimum -- vs. in a monolithic world a plugin that only needs Identity+Node ends up implementing funcs that return "not implemented" for all the controller-type RPCs.

**Comment by akutz** [comment]
Hi @jdef,

I get it. I'm just arguing that the boilerplate stuff isn't *that* bad and already has to happen enough to make it part and parcel of developing an SP in Golang. Ultimately I don't really care -- I was just trying to present one possible scenario that would eliminate too much time spent on what RPC should go where.
