### ISSUE TITLE
Volume Type support capabilities

### ISSUE THREAD

**Issue by lpabon** [container-storage-interface/spec#187]
While creating csi-sanity tool, we had to "guess" what type of volumes the system supported. It would be great to have a VolumeCapability or something like that where it would return if the following is supported:

* CapacityRange: Does Create require CapacityRange. Example, NFS does not, but others will require it.
* Block: Does the device support raw block mounts.

**Comment by lpabon** [comment]
After discussing during the CSI call, we agreed that the driver should return a UNIMPLEMENTED.

**Comment by jdef** [comment]
I'm not convinced that UNIMPLEMENTED is the right thing to do -- I think
CSI normally uses that to indicate that a particular RPC has not been
implemented, not that a particular volume-feature is somehow unsupported.
This needs more thought.

**Comment by akutz** [comment]
I didn't think we said `UNIMPLEMENTED`, I was pretty sure we said `UNSUPPORTED`, but now I see that doesn't exist. I recommend `InvalidArgument` and that we investigate creating new protobuf error message types to indicate additional error details. Because ultimately, this really is a case of an invalid argument, the volume capability.
