### ISSUE TITLE
Consider making ValidateVolumeCapabilitesRequest align with CreateVolumeRequest

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#242]
Paraphrased from https://github.com/container-storage-interface/spec/pull/188#discussion_r191543503:

The arguments to `ValidateVolumeCapability` should be consistent with those in `CreateVolumeRequest` (i.e., `CapacityRange`, `TopologyRequirement`, etc.) because that's what COs should care about when dealing with pre-existing volumes the same way as if they're dealing with dynamically provisioned volumes.

**Comment by CTrox** [comment]
I would also welcome this change, specifically if I had access to the same secrets as in `CreateVolumeRequest`. As `ValidateVolumeCapabilities` requires me to check if the requested volume already exists, I cannot do that without having a single secret bound to this controller instance.

**Comment by jdef** [comment]
This is becoming increasingly important for Mesos w/ respect to reasoning about pre-existing volumes.

**Comment by jdef** [comment]
Somewhat related, it was brought up in a recent community sync that the validation API isn't very forward-compatible. Let's say that new features are added to CSI that require validation by the plugin: the ValidateVolumeCapabilitiesRequuest message is updated w/ a new field for this. A plugin based on an older spec will ignore the new field and may return a "validation successful" response. This is misleading since the old plugin probably doesn't support the new feature that the CO may have been attempting to validate.
