### ISSUE TITLE
Clarify MountVolume in VolumeCapability

### ISSUE THREAD

**Issue by govint** [container-storage-interface/spec#26]
Can the spec be updated to detail what MountVolume type of volume covers?  Volumes can be created on a NFS share and surfaced to containers. An _fs type_ won't apply to these volumes. How are blob or object stores supported with this model?  Or for that matter _local_ volumes

**Comment by julian-hj** [comment]
Unless I am missing something, I think those examples are out of scope for this proposal, which is really about provisioning storage and making it available on the node host so that it can be bind-mounted into a container.

Object stores would normally be accessed via an S3 or Swift client or some similar network protocol, and therefore won't be bind-mounted and don't need to go through this plugin interface.

Local storage can be bind-mounted directly into the container by the CO, without a plugin, so it is difficult to know why anyone would bother to make a local storage plugin, unless they were doing it just to test the framework.

**Comment by cpuguy83** [comment]
@govint This is why `fs_type` and `mount_flags` are optional.
So far we've only really discussed block and file, maybe we need to look at others? How would you expose these to a container?

**Comment by saad-ali** [comment]
NFS will will set fstype to empty. Blob/object storage is not supported by CSI. Local storage is supported and we don't have any known issues with it.
