### ISSUE TITLE
Why use the Statefulset to deploy CSI plugins ?

### ISSUE THREAD

**Issue by illusion202** [container-storage-interface/spec#364]

**Comment by shay-berman** [comment]
Hi @illusion202

Full detail about why stateful-set is the recommended way to deploy the CSI controller -> https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md#recommended-mechanism-for-deploying-csi-drivers-on-kubernetes.

Anyway, I think that this repository is not the right place to ask these questions, because this is the CSI generic specification which is not related to any orchestrator type (like Kubernetes).

You can see more detail about CSI driver in kubernetes -> https://kubernetes-csi.github.io/docs/deploying.html

Thanks
Shay

**Comment by illusion202** [comment]
@shay-berman Got it. Thanks a lot.

**Comment by illusion202** [comment]
@shay-berman By the way, can you refer to any cases of 'Deployment with multiple replicas and leader election enabled'.

**Comment by shay-berman** [comment]
Hi @illusion202

I didn't see anyone who implemented CSI controller with replica>1.  Usually replica=1 is good enough because you have high availability by k8s that make sure the controller will be up and running all the time in the cluster (and if it fails, it will take few seconds until controller is back to run again). 

But your CSI controller has a lot of traffic (maybe you have use case the k8s cluster creates all the time PVCs\start and stop many pods all the time simultaneously) then having replica>1 could make sense.   is this your use case?

**Comment by illusion202** [comment]
> Hi @illusion202
> 
> I didn't see anyone who implemented CSI controller with replica>1. Usually replica=1 is good enough because you have high availability by k8s that make sure the controller will be up and running all the time in the cluster (and if it fails, it will take few seconds until controller is back to run again).
> 
> But your CSI controller has a lot of traffic (maybe you have use case the k8s cluster creates all the time PVCs\start and stop many pods all the time simultaneously) then having replica>1 could make sense. is this your use case?

**Comment by illusion202** [comment]
> Hi @illusion202
> 
> I didn't see anyone who implemented CSI controller with replica>1. Usually replica=1 is good enough because you have high availability by k8s that make sure the controller will be up and running all the time in the cluster (and if it fails, it will take few seconds until controller is back to run again).
> 
> But your CSI controller has a lot of traffic (maybe you have use case the k8s cluster creates all the time PVCs\start and stop many pods all the time simultaneously) then having replica>1 could make sense. is this your use case?
<--- That`s it. And would you please introduce the difference between two ways (Statefulset & Deployment) of deploying CSI plugins, I couldn`t find answer from -> https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md#recommended-mechanism-for-deploying-csi-drivers-on-kubernetes.

**Comment by pohly** [comment]
Jay Lee <notifications@github.com> writes:
> And would you please introduce the difference between
> two ways (Statefulset & Deployment) of deploying CSI plugins, I
> couldn`t find answer from ->
> https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md#recommended-mechanism-for-deploying-csi-drivers-on-kubernetes.

I've filed an issue for this, see https://github.com/kubernetes-csi/docs/issues/138
