### ISSUE TITLE
Proposal: support Domain as a first-class field

### ISSUE THREAD

**Issue by jdef** [container-storage-interface/spec#7]
Volume locality is important for both COs and SPs:
* COs may strategically place volumes to optimize workloads for throughput, availability, etc.
  * This is likely based on the CO's knowledge of the node topology (e.g. region, rack, etc.)
  * As per #43 not all nodes in the cluster may have the same connectivity to backend storage. The CO must take this into account when placing workloads that depend on a particular backend.
* SPs may strategically place volumes to optimize (especially when guidance is not provided by a CO).
  * The fault domain(s) of the backend storage may not align with the fault domain(s) of the node(s) to which volumes are attached. Furthermore, placing 100% of the volume placement burden on the CO may be problematic: the domain topology of the backend storage may be sufficiently complex as to significantly complicate placement logic in the CO (and lowers the chances that all CO's will properly implement such complex placement strategies).
  * There is very likely a need to separate the concept of **origin domain** (where the volume lives within backend storage) from **target domain** (where the volume is attached on the cluster)
  * As per #44 CSI should consider APIs that allow CO's to express, at a high level, volume placement concerns with respect to the origin domain. Perhaps via affinity/anti-affinity volume constraints. It's likely that such APIs will not be supported by all plugins; plugins should probably opt-in to the API via capabilities.
* A pre-created volume's location may determine it's viability for specific workloads
* ... and probably other reasons.

One way to represent volume locality is by "fault domain". Below are some options for representing this concept in CSI:

```protobuf
// Option 1:
message Domain {
  message Zone {
    string value;
  }
  message Region {
    string value;
  }
  // TODO: add NODE_ID
  Zone zone; // OPTIONAL
  Region region; // OPTIONAL
}

// Option 2: Enforced domain hierarchy
message Domain {
  message Region {
    required string value
  }
  message Zone {
    required string value
    Region region
  }
  message Node {
    required NodeID node_id
    oneof parent {
      Zone zone
      Region region
    }
  }
  oneof value {
    Region	region
    Zone	zone
    Node	node
  }
}

// Option 3: Support variable topologies.
// - Can topologies be described in capabilities?
// - How do CO’s understand/reason about variable topologies?
// - How might a CO cope with structural topology changes over time?
message Domain {
  required string unit = 1;	// for example “zone”
  string value = 2;
  parent Domain = 3;
}
```

Some additional questions to consider:
  - Should the `Node` service report the `Domain` of the node, if any?
  - What is the relationship between capacity and domain?

**Comment by jfremy** [comment]
Regarding #43, I think this requires a slightly different solution closer to what @cpuguy83 suggested in the limited topology thread.
There are two things that are being discussed:
- connectivity between a node and a volume
- ensuring that sets of volumes belong to different volumes failure domains
And I think they call for different solutions.

I believe the connectivity question should be kept "hidden" as much as possible from the CO. There could be a lot of storage backend specific logic involved. It would definitely make sense to have an API call that can answer "can I connect this node to this volume?" (or more general: "which of those nodes can connect to this set of volumes?" for efficiency sake). The CO scheduler would be able to make use of this to select the node to run on.

As for the failure domain, the U/C that have been mentioned require knowledge that only the CO has. So the CSI must surface to the CO that it can use to make a decision. 
The failure domain can probably be requested manually when specifying the volume characteristics; but it would be nice if the CO could discover them from CSI. That would allow scenario where the user asks the CO to use volumes from distinct volume failure domains rather than explicitly specifying each volume failure domains to use. When you have a few failure domains, it's fine to specify them manually but if there are a lot of them, then it is more convenient to express requirements based on volumes belonging to different failure domains. And this does not preclude from manually specifying the failure domain when desired.

The only other thing I'd add regarding the failure domain is that it needs to be "understood" by the CO. It must be able to compare two failure domains and figure out if they're the same or not. So that will require each field in the structure to have a clear meaning.

**Comment by jdef** [comment]
> The only other thing I'd add regarding the failure domain is that it needs to be "understood" by the CO. It must be able to compare two failure domains and figure out if they're the same or not. So that will require each field in the structure to have a clear meaning.

Backend storage systems are complicated. It may not be reasonable for CO's to understand the nature of fault domains that exist within backend systems. We should probably consider an API to more abstractly express the intent of an operation in terms of node and/or volume affinity/anti-affinity: Node affinity could perhaps be expressed in terms of Domain (if we had a decent way to model Node/Domain relationships). Current thinking is that Domain (as per the options presented above) is unlikely to capture the potential complexity of fault domains within backend storage systems.

**Comment by saad-ali** [comment]
We added accessibility topology in #188 
We will consider exposing storage topology that does not effect accessibility after 1.0.

**Comment by saad-ali** [comment]
Storage topology request is being tracked in https://github.com/container-storage-interface/spec/issues/44. Will close this issue.
